// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rocketdomainmock

import (
	"context"
	"github.com/soulcodex/rockets-message-processor/internal/rocket/domain"
	"sync"
)

// Ensure, that RocketRepositoryMock does implement rocketdomain.RocketRepository.
// If this is not the case, regenerate this file with moq.
var _ rocketdomain.RocketRepository = &RocketRepositoryMock{}

// RocketRepositoryMock is a mock implementation of rocketdomain.RocketRepository.
//
//	func TestSomethingThatUsesRocketRepository(t *testing.T) {
//
//		// make and configure a mocked rocketdomain.RocketRepository
//		mockedRocketRepository := &RocketRepositoryMock{
//			FindFunc: func(ctx context.Context, id rocketdomain.RocketID) (*rocketdomain.Rocket, error) {
//				panic("mock out the Find method")
//			},
//			SaveFunc: func(ctx context.Context, r *rocketdomain.Rocket) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedRocketRepository in code that requires rocketdomain.RocketRepository
//		// and then make assertions.
//
//	}
type RocketRepositoryMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id rocketdomain.RocketID) (*rocketdomain.Rocket, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, r *rocketdomain.Rocket) error

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID rocketdomain.RocketID
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R *rocketdomain.Rocket
		}
	}
	lockFind sync.RWMutex
	lockSave sync.RWMutex
}

// Find calls FindFunc.
func (mock *RocketRepositoryMock) Find(ctx context.Context, id rocketdomain.RocketID) (*rocketdomain.Rocket, error) {
	if mock.FindFunc == nil {
		panic("RocketRepositoryMock.FindFunc: method is nil but RocketRepository.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  rocketdomain.RocketID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedRocketRepository.FindCalls())
func (mock *RocketRepositoryMock) FindCalls() []struct {
	Ctx context.Context
	ID  rocketdomain.RocketID
} {
	var calls []struct {
		Ctx context.Context
		ID  rocketdomain.RocketID
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RocketRepositoryMock) Save(ctx context.Context, r *rocketdomain.Rocket) error {
	if mock.SaveFunc == nil {
		panic("RocketRepositoryMock.SaveFunc: method is nil but RocketRepository.Save was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   *rocketdomain.Rocket
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, r)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedRocketRepository.SaveCalls())
func (mock *RocketRepositoryMock) SaveCalls() []struct {
	Ctx context.Context
	R   *rocketdomain.Rocket
} {
	var calls []struct {
		Ctx context.Context
		R   *rocketdomain.Rocket
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
