services:
  redis:
    image: redis:7.4.1-alpine3.20
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_PORT=6379
